spring:
  datasource:
    url: jdbc:mysql://localhost:3306/securecapita
    username: root
    password: secret
  jpa:
    #database-platform: org.hibernate.dialect.MySQL8DBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      globally_quoted_identifiers: true
      #dialect: org.hibernate.dialect.MySQL8DBDialect
      format_sql: true
  sql:
    init:
      mode: never